/* Copyright (c) 2014 Stanford University
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR(S) DISCLAIM ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL AUTHORS BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package edu.stanford.ramcloud;

/**
 * C++ status codes.
 * Please refer to Status.h for documentation.
 */
public enum Status {
    STATUS_OK,
    STATUS_UNKNOWN_TABLET,
    STATUS_TABLE_DOESNT_EXIST,
    STATUS_OBJECT_DOESNT_EXIST,
    STATUS_OBJECT_EXISTS,
    STATUS_WRONG_VERSION,
    STATUS_NO_TABLE_SPACE,
    STATUS_MESSAGE_TOO_SHORT,
    STATUS_UNIMPLEMENTED_REQUEST,
    STATUS_REQUEST_FORMAT_ERROR,
    STATUS_RESPONSE_FORMAT_ERROR,
    STATUS_COULDNT_CONNECT,
    STATUS_BACKUP_BAD_SEGMENT_ID,
    STATUS_BACKUP_OPEN_REJECTED,
    STATUS_BACKUP_SEGMENT_OVERFLOW,
    STATUS_BACKUP_MALFORMED_SEGMENT,
    STATUS_SEGMENT_RECOVERY_FAILED,
    STATUS_RETRY,
    STATUS_SERVICE_NOT_AVAILABLE,
    STATUS_TIMEOUT,        
    STATUS_SERVER_NOT_UP,
    STATUS_INTERNAL_ERROR,
    STATUS_INVALID_OBJECT,
    STATUS_TABLET_DOESNT_EXIST,
    STATUS_PARTITION_BEFORE_READ,
    STATUS_WRONG_SERVER,
    STATUS_CALLER_NOT_IN_CLUSTER,
    STATUS_REQUEST_TOO_LARGE,
    STATUS_UNKNOWN_INDEXLET,
    STATUS_UNKNOWN_INDEX,
    STATUS_INVALID_PARAMETER;
    
    public static final Status[] statuses = Status.values();
}
