#!/bin/bash

source scripts/common.bash

port=11114

portslay $port

$OBJDIR/server -L tcp:host=127.0.0.1,port=$port > /dev/null 2>&1 &
sleep .1

retval=$($OBJDIR/client -s tcp:host=127.0.0.1,port=$port > /dev/null)

portslay $port

exit $retval
