#!/bin/bash

# Skip this check if there is not a valid repository (can happen when
# cross-debugging with NetBeans, for example).
git status 2>&1 > /dev/null
if [[ "$?" != "0" ]]; then
        exit
fi

git diff --quiet
if [[ "$?" != "0" ]]; then
	echo "*********************************************************"
	echo "WARNING: uncommited changes, working directory not clean."
	git diff --shortstat
	echo "*********************************************************"
fi
exit
