#!/bin/bash
export PYTHONPATH=bindings/python
OBJSUFFIX=$(git symbolic-ref -q HEAD | \
	       sed -e s,refs/heads/,.,)
OBJDIR=obj$OBJSUFFIX
export LD_LIBRARY_PATH=$OBJDIR
exec python src/tests/rc-smack.py 10 > /dev/null
