#!/bin/bash

PYERRORS=$( make --silent python-docs 2>&1 | egrep \(Warning\|Error\) | wc -l )
if [ $PYERRORS -gt 0 ]; then
    echo "Fix your Python documentation warnings first!"
fi

make --silent docs-check 2>&1 >/dev/null
CERRORS=$?
if [ $CERRORS -ne 0 ]; then
    echo "Fix your C/C++ documentation warnings first! (run make docs-check)"
fi

exit $(( $PYERRORS + $CERRORS ))
