#!/bin/bash

source scripts/common.bash

port=11114
cport=$(( $port + 1 ))

masterLocator=basic+udp:host=127.0.0.1,port=$port
coordinatorLocator=basic+udp:host=127.0.0.1,port=$cport

portslay $port
portslay $cport

atexit "portslay $port"
atexit "portslay $cport"

$OBJDIR/coordinator -C $coordinatorLocator > /dev/null 2>&1 &
sleep .1
$OBJDIR/server -M -L $masterLocator -C $coordinatorLocator > /dev/null 2>&1 &
sleep .1

$APPOBJDIR/client -C $coordinatorLocator > /dev/null 2>&1
retval=$?

exit $retval
