#!/bin/bash

# these scripts are intended to be run from the top level
# of the project

port=11113

source scripts/common.bash

portslay $port

atexit "portslay $port"

# Start a server and run tests
$OBJDIR/server -L fast+udp:host=127.0.0.1,port=$port > /dev/null 2>&1 &
sleep .1

$OBJDIR/Bench -s fast+udp:host=127.0.0.1,port=$port $*
RETVAL=$?

exit $RETVAL
