#!/bin/bash

# these scripts are intended to be run from the top level
# of the project

port=11113

source scripts/common.bash

portslay $port

# Start a server and run tests
$OBJDIR/server -p $port > /dev/null 2>&1 &
sleep .1

$OBJDIR/Bench -p $port $*
RETVAL=$?

portslay $port

exit $RETVAL
