#!/bin/bash

umask 0000

source ./scripts/common.bash

# these keep constant written data (640MB)
#counts[128]=5242880
#counts[256]=2621440
#counts[512]=1310720
#counts[1024]=655360
#counts[2048]=327680
#counts[4096]=163840
#counts[8192]=81920

# these keep constant logged data (640MB)
counts[128]=3812983
counts[256]=2207516
counts[512]=1198366
counts[1024]=626012
counts[2048]=320174
counts[4096]=161941
counts[8192]=81442

IFS=

# The different configurations to test
# and Names for the configurations, they appear in the graph legend for each series
flags[0]=EXTRACXXFLAGS="-DFOO"
name[0]='Normal'
flags[1]=EXTRACXXFLAGS="-DPERF_DEBUG_RECOVERY_REC_SEG_JUST_ITER"
name[1]='recoverSegment just SegmentIterator'
flags[2]=EXTRACXXFLAGS="-DPERF_DEBUG_RECOVERY_REC_SEG_NO_HT"
name[2]='recoverSegment no Hashtable'
flags[3]=EXTRACXXFLAGS="-DPERF_DEBUG_RECOVERY_REC_SEG_NO_LOG"
name[3]='recoverSegment no Logging'
flags[4]=EXTRACXXFLAGS="-DPERF_DEBUG_RECOVERY_REC_SEG_NO_PREFETCH"
name[4]='recoverSegment no prefetching'
flags[5]=EXTRACXXFLAGS="-DPERF_DEBUG_RECOVERY_NO_CKSUM"
name[5]='No checksum'
flags[6]=EXTRACXXFLAGS="-DPERF_DEBUG_RECOVERY_SOFTWARE_CRC32"
name[6]='Software crc32'
flags[7]=EXTRACXXFLAGS="-DPERF_DEBUG_RECOVERY_SERIAL"
name[7]='recoverSegment serial'

# clean up old results and start a new gnuplot file
rm /tmp/recovery-results-*
echo -n 'set terminal png
set output "/tmp/recovery.png"
set title "Recovery Time for 640 MB of log data with 1 In-Memory Backup"
set xlabel "Inserts (Millions)"
set ylabel "Recovery Time (ms)"
set xrange [0:4]
set yrange [0:]
set grid ytics

plot ' > /tmp/recovery-gnuplot

i=0
while [ "${flags[i]}" != "" ]; do
    echo ${flags[i]} >> /tmp/recovery-results-$i
    make clean 2>&1 || continue;
    make CXX=g++44 DEBUG=no ${flags[i]} -j 8 || continue;
    for size in 8192 4096 2048 1024 512 256 128; do
        count=${counts[$size]}
        ./scripts/recovery -s $size -n $count
        ## extract the results from the run log and concat them
        awk '
        /Performing/ { count=$8; size=$11; }
        /Recovery completed in/ { ns=$10; }
        /Bytes written/ { if ($9 != 0) { written=$9; } }
        /Bytes logged/ { if ($10 != 0) { logged=$10; } }
        END { print (count/1000000) " " size " " written " " logged " " (ns/1000); }
        ' /tmp/rclog >> /tmp/recovery-results-$i
    done
    if [ "$i" != "0" ]; then
        echo ", \\" >> /tmp/recovery-gnuplot
    fi
    echo -n "\"/tmp/recovery-results-${i}\" using 1:5 with linespoints title \"${name[i]}\"" >> /tmp/recovery-gnuplot
    i=$((i+1))
done
gnuplot /tmp/recovery-gnuplot
