#!/bin/bash

# these scripts are intended to be run from the top level
# of the project

port=11113
cport=$(( $port + 1 ))

source scripts/common.bash

transport=tcp
ip=`hostname -i`

masterLocator=$transport:host=$ip,port=$port
coordinatorLocator=$transport:host=$ip,port=$cport

# Check to see if master and coordinator servers are running. If so, kill 'em!
portslay $port
portslay $cport

atexit "portslay $port"
atexit "portslay $cport"

# Start a server and run tests
$OBJDIR/coordinator -C $coordinatorLocator &
$OBJDIR/server -L $masterLocator -C $coordinatorLocator &
sleep .1

# now call perl script to do the rest of the work
# scripts/latencyVSsize.pl -co $coordinatorLocator -b $OBJDIR/Bench -t $transport --dump $transport.size.dump
scripts/latencyVSload.pl -co $coordinatorLocator -b $OBJDIR/Bench -t $transport --dump $transport.load.dump -cl rc0[2-7].scs.stanford.edu
RETVAL=$?

exit $RETVAL

