#!/bin/bash

# these scripts are intended to be run from the top level
# of the project

TOP=$(pwd)
REPO=git://fiz.stanford.edu/git/ramcloud.git
LOGDIR=$(pwd)
LOG="$LOGDIR/nightly.log"
DATE=$(date +%Y-%m-%d)
BUILDDIR=/tmp/ramcloud-nightly-build-$DATE
BUILDLOG=$LOGDIR/nightly-build-$DATE.log

# do actual build and test
rm -rf $BUILDDIR
git clone $REPO $BUILDDIR
pushd $BUILDDIR
make obj.master/server > $BUILDLOG 2>&1 
make obj.master/Bench > $BUILDLOG 2>&1 
$TOP/scripts/run-bench >> $LOG
popd
rm -rf $BUILDDIR

# generate graph
gnuplot scripts/nightly.gnu
