#!/bin/bash

# these scripts are intended to be run from the top level
# of the project

port=11113
cport=$(( $port + 1 ))

source scripts/common.bash

masterLocator=fast+udp:host=127.0.0.1,port=$port
coordinatorLocator=fast+udp:host=127.0.0.1,port=$cport

if [ $# -eq 1 ]; then
    if [ $1 == "infrc" ]; then
        masterLocator=infrc:host=127.0.0.1,port=$port
        coordinatorLocator=infrc:host=127.0.0.1,port=$cport
    elif [ $1 == "infud" ]; then
        masterLocator="fast+infud:"
        coordinatorLocator="fast+udp:host=127.0.0.1,port=$cport;fast+infud:"
    elif [ $1 == "tcp" ]; then
        masterLocator=tcp:host=127.0.0.1,port=$port
        coordinatorLocator=tcp:host=127.0.0.1,port=$cport
    fi
fi

# Check to see if master and coordinator servers are running. If so, kill 'em!
portslay $port
portslay $cport

atexit "portslay $port"
atexit "portslay $cport"

VER=$(git log -1 | grep '^commit' | awk '{print $2;}')
DATE=$(git log -1 --date=short | grep '^Date:' | awk '{print $2;}')

# Start a server and run tests
$OBJDIR/coordinator -C "$coordinatorLocator" &
$OBJDIR/server -L "$masterLocator" -C "$coordinatorLocator" &
sleep .1

VAL=$($OBJDIR/Bench -C "$coordinatorLocator" -R -S 1000 -n 10000 | \
    grep '^readMany avgns' | awk '{print $3;}')
RETVAL=$?

echo "$DATE $VER $VAL ns"

exit $RETVAL
