#!/bin/bash

# these scripts are intended to be run from the top level
# of the project

port=11113

source scripts/common.bash

portslay $port

VER=$(git log -1 | grep '^commit' | awk '{print $2;}')
DATE=$(git log -1 --date=short | grep '^Date:' | awk '{print $2;}')

# Start a server and run tests
$OBJDIR/server -L fast+udp:host=0.0.0.0,port=$port > /dev/null 2>&1 &
sleep .1

VAL=$($OBJDIR/Bench -s fast+udp:host=127.0.0.1,port=$port -R -S 1000 -n 10000 | \
        grep '^readMany avgns' | awk '{print $3;}')
RETVAL=$?

portslay $port

echo "$DATE $VER $VAL"
exit $RETVAL
